/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj2.lightout;

import java.awt.Color;
import static java.awt.Color.BLACK;
import static java.awt.Color.WHITE;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author emerson / paulo / jessica / carol
 */
  

public class TelaJogo extends javax.swing.JFrame  {
    
    int controle=1;
    private Timer t;
    private int cont = 0; 

    Funcao func = new Funcao();

    
    public TelaJogo() {
        initComponents();

        PainelConcluido.setVisible(false);
        fim.setVisible(false);
        filmeFim.setVisible(false);
        
       
        
        
        
        
        B1.setBackground(WHITE);    B2.setBackground(WHITE);    B6.setBackground(WHITE);
        B4.setBackground(WHITE);    B5.setBackground(WHITE);    B10.setBackground(WHITE);
        B8.setBackground(WHITE);    B12.setBackground(WHITE);    B13.setBackground(WHITE);
        B14.setBackground(WHITE);    B16.setBackground(WHITE);    B18.setBackground(WHITE);
        B20.setBackground(WHITE);    B21.setBackground(WHITE);    B22.setBackground(WHITE);
        B24.setBackground(WHITE);    B25.setBackground(WHITE);
        
        B3.setBackground(BLACK);    B7.setBackground(BLACK);    B9.setBackground(BLACK);
        B11.setBackground(BLACK);    B15.setBackground(BLACK);    B17.setBackground(BLACK);
        B19.setBackground(BLACK);    B23.setBackground(BLACK);
        
        
         auxTrocarCor();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelConcluido = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        BotConcluido = new javax.swing.JButton();
        saidaConc = new javax.swing.JLabel();
        filmeFim = new javax.swing.JLabel();
        infNivel = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        fim = new javax.swing.JDesktopPane();
        BotLuz = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Tela1 = new javax.swing.JDesktopPane();
        B1 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B11 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B12 = new javax.swing.JButton();
        B15 = new javax.swing.JButton();
        B14 = new javax.swing.JButton();
        B13 = new javax.swing.JButton();
        B20 = new javax.swing.JButton();
        B16 = new javax.swing.JButton();
        B19 = new javax.swing.JButton();
        B22 = new javax.swing.JButton();
        B17 = new javax.swing.JButton();
        B23 = new javax.swing.JButton();
        B21 = new javax.swing.JButton();
        B25 = new javax.swing.JButton();
        B24 = new javax.swing.JButton();
        B18 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj2/lightout/Sprite/pessoa.gif"))); // NOI18N
        PainelConcluido.add(jLabel1);
        jLabel1.setBounds(250, 0, 80, 80);

        BotConcluido.setText("Continuar");
        BotConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotConcluidoActionPerformed(evt);
            }
        });
        PainelConcluido.add(BotConcluido);
        BotConcluido.setBounds(130, 70, 90, 23);

        saidaConc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj2/lightout/Sprite/conc.png"))); // NOI18N
        saidaConc.setText("jLabel1");
        PainelConcluido.add(saidaConc);
        saidaConc.setBounds(0, 0, 350, 110);

        getContentPane().add(PainelConcluido);
        PainelConcluido.setBounds(70, 120, 350, 110);

        filmeFim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj2/lightout/Sprite/filmefinal.gif"))); // NOI18N
        getContentPane().add(filmeFim);
        filmeFim.setBounds(0, 0, 500, 350);

        infNivel.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        infNivel.setForeground(new java.awt.Color(255, 255, 255));
        infNivel.setText("Nivel 1");
        getContentPane().add(infNivel);
        infNivel.setBounds(10, 40, 50, 17);

        reset.setText("Reiniciar");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(373, 300, 100, 23);

        BotLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj2/lightout/Sprite/int.png"))); // NOI18N
        BotLuz.setText("jButton1");
        BotLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLuzActionPerformed(evt);
            }
        });
        fim.add(BotLuz);
        BotLuz.setBounds(370, 230, 90, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj2/lightout/Sprite/telafim.png"))); // NOI18N
        fim.add(jLabel3);
        jLabel3.setBounds(0, 0, 500, 350);

        getContentPane().add(fim);
        fim.setBounds(0, 0, 500, 350);

        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        Tela1.add(B1);
        B1.setBounds(0, 0, 50, 50);

        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        Tela1.add(B5);
        B5.setBounds(200, 0, 50, 50);

        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        Tela1.add(B2);
        B2.setBounds(50, 0, 50, 50);

        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        Tela1.add(B3);
        B3.setBounds(100, 0, 50, 50);

        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        Tela1.add(B4);
        B4.setBounds(150, 0, 50, 50);

        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        Tela1.add(B6);
        B6.setBounds(0, 50, 50, 50);

        B10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10ActionPerformed(evt);
            }
        });
        Tela1.add(B10);
        B10.setBounds(200, 50, 50, 50);

        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        Tela1.add(B7);
        B7.setBounds(50, 50, 50, 50);

        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });
        Tela1.add(B8);
        B8.setBounds(100, 50, 50, 50);

        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B11ActionPerformed(evt);
            }
        });
        Tela1.add(B11);
        B11.setBounds(0, 100, 50, 50);

        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        Tela1.add(B9);
        B9.setBounds(150, 50, 50, 50);

        B12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B12ActionPerformed(evt);
            }
        });
        Tela1.add(B12);
        B12.setBounds(50, 100, 50, 50);

        B15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B15ActionPerformed(evt);
            }
        });
        Tela1.add(B15);
        B15.setBounds(200, 100, 50, 50);

        B14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B14ActionPerformed(evt);
            }
        });
        Tela1.add(B14);
        B14.setBounds(150, 100, 50, 50);

        B13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B13ActionPerformed(evt);
            }
        });
        Tela1.add(B13);
        B13.setBounds(100, 100, 50, 50);

        B20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B20ActionPerformed(evt);
            }
        });
        Tela1.add(B20);
        B20.setBounds(200, 150, 50, 50);

        B16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B16ActionPerformed(evt);
            }
        });
        Tela1.add(B16);
        B16.setBounds(0, 150, 50, 50);

        B19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B19ActionPerformed(evt);
            }
        });
        Tela1.add(B19);
        B19.setBounds(150, 150, 50, 50);

        B22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B22ActionPerformed(evt);
            }
        });
        Tela1.add(B22);
        B22.setBounds(50, 200, 50, 50);

        B17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B17ActionPerformed(evt);
            }
        });
        Tela1.add(B17);
        B17.setBounds(50, 150, 50, 50);

        B23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B23ActionPerformed(evt);
            }
        });
        Tela1.add(B23);
        B23.setBounds(100, 200, 50, 50);

        B21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B21ActionPerformed(evt);
            }
        });
        Tela1.add(B21);
        B21.setBounds(0, 200, 50, 50);

        B25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B25ActionPerformed(evt);
            }
        });
        Tela1.add(B25);
        B25.setBounds(200, 200, 50, 50);

        B24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B24ActionPerformed(evt);
            }
        });
        Tela1.add(B24);
        B24.setBounds(150, 200, 50, 50);

        B18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B18ActionPerformed(evt);
            }
        });
        Tela1.add(B18);
        B18.setBounds(100, 150, 50, 50);

        getContentPane().add(Tela1);
        Tela1.setBounds(10, 70, 250, 250);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj2/lightout/Sprite/001.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 350);

        setSize(new java.awt.Dimension(516, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        func.trocarCor(B1);
        func.trocarCor(B2);
        func.trocarCor(B6);
        NivelConcluido(B1);
        
         
        
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        func.trocarCor(B2);
        func.trocarCor(B1);
        func.trocarCor(B3);
        func.trocarCor(B7);
        NivelConcluido(B2);
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        func.trocarCor(B3);
        func.trocarCor(B2);
        func.trocarCor(B4);
        func.trocarCor(B8);
        NivelConcluido(B3);
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        func.trocarCor(B4);
        func.trocarCor(B3);
        func.trocarCor(B5);
        func.trocarCor(B9);
        NivelConcluido(B4);
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        func.trocarCor(B4);
        func.trocarCor(B5);
        func.trocarCor(B10);
        NivelConcluido(B5);
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        func.trocarCor(B6);
        func.trocarCor(B1);
        func.trocarCor(B7);
        func.trocarCor(B11);
        NivelConcluido(B6);
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        func.trocarCor(B7);
       func. trocarCor(B2);
       func. trocarCor(B6);
       func. trocarCor(B8);
       func. trocarCor(B12);
       NivelConcluido(B7);
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        func.trocarCor(B8);
       func. trocarCor(B3);
       func. trocarCor(B7);
       func. trocarCor(B9);
       func. trocarCor(B13);
       NivelConcluido(B8);
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
       func. trocarCor(B9);
       func. trocarCor(B4);
       func. trocarCor(B8);
       func. trocarCor(B10);
       func. trocarCor(B14);
       NivelConcluido(B9);
    }//GEN-LAST:event_B9ActionPerformed

    private void B10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B10ActionPerformed
       func. trocarCor(B10);
       func. trocarCor(B5);
       func. trocarCor(B9);
       func. trocarCor(B15);
       NivelConcluido(B10);
    }//GEN-LAST:event_B10ActionPerformed

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B11ActionPerformed
       func. trocarCor(B11);
       func. trocarCor(B6);
       func. trocarCor(B12);
       func. trocarCor(B16);
       NivelConcluido(B11);
    }//GEN-LAST:event_B11ActionPerformed

    private void B12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B12ActionPerformed
       func. trocarCor(B12);
       func. trocarCor(B7);
       func. trocarCor(B11);
       func. trocarCor(B13);
       func. trocarCor(B17);
        NivelConcluido(B12);
    }//GEN-LAST:event_B12ActionPerformed

    private void B13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B13ActionPerformed
        func.trocarCor(B13);
       func. trocarCor(B8);
       func. trocarCor(B12);
       func. trocarCor(B14);
      func.  trocarCor(B18);
       NivelConcluido(B13);
    }//GEN-LAST:event_B13ActionPerformed

    private void B14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B14ActionPerformed
       func. trocarCor(B14);
       func. trocarCor(B9);
       func. trocarCor(B13);
       func. trocarCor(B15);
       func. trocarCor(B19);
       NivelConcluido(B14);
    }//GEN-LAST:event_B14ActionPerformed

    private void B15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B15ActionPerformed
       func. trocarCor(B15);
       func. trocarCor(B10);
        func.trocarCor(B14);
       func. trocarCor(B20);
        NivelConcluido(B15);
    }//GEN-LAST:event_B15ActionPerformed

    private void B16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B16ActionPerformed
      func.trocarCor(B16);
       func. trocarCor(B11);
       func. trocarCor(B17);
       func. trocarCor(B21);
       NivelConcluido(B16);
    }//GEN-LAST:event_B16ActionPerformed

    private void B17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B17ActionPerformed
       func. trocarCor(B17);
       func.trocarCor(B12);
       func. trocarCor(B16);
       func. trocarCor(B18);
       func. trocarCor(B22);
        NivelConcluido(B17);
    }//GEN-LAST:event_B17ActionPerformed

    private void B18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B18ActionPerformed
        func.trocarCor(B18);
        func.trocarCor(B13);
       func. trocarCor(B17);
        func.trocarCor(B19);
       func. trocarCor(B23);
       NivelConcluido(B18);
    }//GEN-LAST:event_B18ActionPerformed

    private void B19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B19ActionPerformed
       func.trocarCor(B19);
       func. trocarCor(B14);
       func. trocarCor(B18);
       func. trocarCor(B20);
       func. trocarCor(B24);
       NivelConcluido(B19);
    }//GEN-LAST:event_B19ActionPerformed

    private void B20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B20ActionPerformed
       func. trocarCor(B20);
        func.trocarCor(B15);
       func. trocarCor(B19);
       func. trocarCor(B25);
       NivelConcluido(B20);
    }//GEN-LAST:event_B20ActionPerformed

    private void B21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B21ActionPerformed
     func.  trocarCor(B21);
       func. trocarCor(B16);
      func.  trocarCor(B22);
      NivelConcluido(B21);
      
      
    }//GEN-LAST:event_B21ActionPerformed

    private void B22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B22ActionPerformed
       func. trocarCor(B22);
       func. trocarCor(B17);
       func. trocarCor(B21);
       func. trocarCor(B23);
        NivelConcluido(B22);
    }//GEN-LAST:event_B22ActionPerformed

    private void B23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B23ActionPerformed
      func.  trocarCor(B23);
       func. trocarCor(B18);
       func. trocarCor(B22);
       func. trocarCor(B24);
        NivelConcluido(B23);
    }//GEN-LAST:event_B23ActionPerformed

    private void B24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B24ActionPerformed
      func. trocarCor(B24);
       func. trocarCor(B19);
       func. trocarCor(B23);
       func. trocarCor(B25);
      NivelConcluido(B24);
    }//GEN-LAST:event_B24ActionPerformed

    private void B25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B25ActionPerformed
       func. trocarCor(B25);
        func.trocarCor(B20);
       func. trocarCor(B24);
       NivelConcluido(B25);
    }//GEN-LAST:event_B25ActionPerformed

    private void BotConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotConcluidoActionPerformed
       mudarNivel();
    }//GEN-LAST:event_BotConcluidoActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        
        if(controle==1){
        B1.setBackground(WHITE);    B2.setBackground(WHITE);    B6.setBackground(WHITE);
        B4.setBackground(WHITE);    B5.setBackground(WHITE);    B10.setBackground(WHITE);
        B8.setBackground(WHITE);    B12.setBackground(WHITE);    B13.setBackground(WHITE);
        B14.setBackground(WHITE);    B16.setBackground(WHITE);    B18.setBackground(WHITE);
        B20.setBackground(WHITE);    B21.setBackground(WHITE);    B22.setBackground(WHITE);
        B24.setBackground(WHITE);    B25.setBackground(WHITE);
        
        B3.setBackground(BLACK);    B7.setBackground(BLACK);    B9.setBackground(BLACK);
        B11.setBackground(BLACK);    B15.setBackground(BLACK);    B17.setBackground(BLACK);
        B19.setBackground(BLACK);    B23.setBackground(BLACK);
        
        auxTrocarCor();
        }
        else if(controle==2){
         B1.setBackground(BLACK);    B2.setBackground(WHITE);    B3.setBackground(BLACK);    B4.setBackground(WHITE);    B5.setBackground(BLACK);
         B6.setBackground(WHITE);    B7.setBackground(WHITE);    B8.setBackground(BLACK);    B9.setBackground(WHITE);    B10.setBackground(WHITE);
         B11.setBackground(BLACK);    B12.setBackground(WHITE);    B13.setBackground(BLACK);    B14.setBackground(WHITE);    B15.setBackground(BLACK);
         B16.setBackground(WHITE);    B17.setBackground(BLACK);    B18.setBackground(WHITE);    B19.setBackground(BLACK);    B20.setBackground(WHITE);
         B21.setBackground(WHITE);    B22.setBackground(BLACK);    B23.setBackground(WHITE);    B24.setBackground(BLACK);    B25.setBackground(WHITE);
         
         auxTrocarCor();
        }
        else if(controle==3){
         B1.setBackground(WHITE);    B2.setBackground(BLACK);    B3.setBackground(BLACK);    B4.setBackground(BLACK);    B5.setBackground(WHITE);
         B6.setBackground(WHITE);    B7.setBackground(WHITE);    B8.setBackground(BLACK);    B9.setBackground(WHITE);    B10.setBackground(WHITE);
         B11.setBackground(BLACK);    B12.setBackground(BLACK);    B13.setBackground(WHITE);    B14.setBackground(BLACK);    B15.setBackground(BLACK);
         B16.setBackground(WHITE);    B17.setBackground(BLACK);    B18.setBackground(WHITE);    B19.setBackground(BLACK);    B20.setBackground(BLACK);
         B21.setBackground(WHITE);    B22.setBackground(BLACK);    B23.setBackground(WHITE);    B24.setBackground(WHITE);    B25.setBackground(BLACK);

         auxTrocarCor();
        }
        else if(controle==4){
            B1.setBackground(WHITE);    B2.setBackground(WHITE);    B3.setBackground(BLACK);    B4.setBackground(WHITE);    B5.setBackground(WHITE);
            B6.setBackground(BLACK);    B7.setBackground(BLACK);    B8.setBackground(BLACK);    B9.setBackground(BLACK);    B10.setBackground(BLACK);
            B11.setBackground(WHITE);    B12.setBackground(WHITE);    B13.setBackground(BLACK);    B14.setBackground(WHITE);    B15.setBackground(WHITE);
            B16.setBackground(BLACK);    B17.setBackground(BLACK);    B18.setBackground(BLACK);    B19.setBackground(BLACK);    B20.setBackground(WHITE);
            B21.setBackground(WHITE);    B22.setBackground(WHITE);    B23.setBackground(BLACK);    B24.setBackground(BLACK);    B25.setBackground(BLACK);

         auxTrocarCor();
        }
        else if(controle==5){
         B1.setBackground(BLACK);    B2.setBackground(WHITE);    B3.setBackground(WHITE);    B4.setBackground(WHITE);    B5.setBackground(BLACK);
         B6.setBackground(WHITE);    B7.setBackground(BLACK);    B8.setBackground(WHITE);    B9.setBackground(BLACK);    B10.setBackground(WHITE);
         B11.setBackground(BLACK);    B12.setBackground(WHITE);    B13.setBackground(WHITE);    B14.setBackground(BLACK);    B15.setBackground(BLACK);
         B16.setBackground(WHITE);    B17.setBackground(BLACK);    B18.setBackground(WHITE);    B19.setBackground(WHITE);    B20.setBackground(WHITE);
         B21.setBackground(WHITE);    B22.setBackground(WHITE);    B23.setBackground(BLACK);    B24.setBackground(WHITE);    B25.setBackground(BLACK);

         auxTrocarCor();
        }
    }//GEN-LAST:event_resetActionPerformed

    private void BotLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLuzActionPerformed
    /*  filmeFim.setVisible(true);
        BotLuz.setVisible(false);
        
        t = new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                
                cont++;
              if(cont==4){
                  System.exit(0);
              }
            }
        });
        t.start();
     */   
        System.exit(0);
        
    }//GEN-LAST:event_BotLuzActionPerformed
        
    public void mudarNivel(){
    
        if(controle==2){
         B1.setBackground(BLACK);    B2.setBackground(WHITE);    B3.setBackground(BLACK);    B4.setBackground(WHITE);    B5.setBackground(BLACK);
         B6.setBackground(WHITE);    B7.setBackground(WHITE);    B8.setBackground(BLACK);    B9.setBackground(WHITE);    B10.setBackground(WHITE);
         B11.setBackground(BLACK);    B12.setBackground(WHITE);    B13.setBackground(BLACK);    B14.setBackground(WHITE);    B15.setBackground(BLACK);
         B16.setBackground(WHITE);    B17.setBackground(BLACK);    B18.setBackground(WHITE);    B19.setBackground(BLACK);    B20.setBackground(WHITE);
         B21.setBackground(WHITE);    B22.setBackground(BLACK);    B23.setBackground(WHITE);    B24.setBackground(BLACK);    B25.setBackground(WHITE);
         
           Tela1.setVisible(true);
           auxTrocarCor();

         
          infNivel.setText("Nivel 2");
         PainelConcluido.setVisible(false);
       }
       else if(controle==3){
         B1.setBackground(WHITE);    B2.setBackground(BLACK);    B3.setBackground(BLACK);    B4.setBackground(BLACK);    B5.setBackground(WHITE);
         B6.setBackground(WHITE);    B7.setBackground(WHITE);    B8.setBackground(BLACK);    B9.setBackground(WHITE);    B10.setBackground(WHITE);
         B11.setBackground(BLACK);    B12.setBackground(BLACK);    B13.setBackground(WHITE);    B14.setBackground(BLACK);    B15.setBackground(BLACK);
         B16.setBackground(WHITE);    B17.setBackground(BLACK);    B18.setBackground(WHITE);    B19.setBackground(BLACK);    B20.setBackground(BLACK);
         B21.setBackground(WHITE);    B22.setBackground(BLACK);    B23.setBackground(WHITE);    B24.setBackground(WHITE);    B25.setBackground(BLACK);

           Tela1.setVisible(true);
           auxTrocarCor();
           
         infNivel.setText("Nivel 3");
         PainelConcluido.setVisible(false);
       }
       else if(controle==4){
            B1.setBackground(WHITE);    B2.setBackground(WHITE);    B3.setBackground(BLACK);    B4.setBackground(WHITE);    B5.setBackground(WHITE);
            B6.setBackground(BLACK);    B7.setBackground(BLACK);    B8.setBackground(BLACK);    B9.setBackground(BLACK);    B10.setBackground(BLACK);
            B11.setBackground(WHITE);    B12.setBackground(WHITE);    B13.setBackground(BLACK);    B14.setBackground(WHITE);    B15.setBackground(WHITE);
            B16.setBackground(BLACK);    B17.setBackground(BLACK);    B18.setBackground(BLACK);    B19.setBackground(BLACK);    B20.setBackground(WHITE);
            B21.setBackground(WHITE);    B22.setBackground(WHITE);    B23.setBackground(BLACK);    B24.setBackground(BLACK);    B25.setBackground(BLACK);

           Tela1.setVisible(true);  
           auxTrocarCor();
           
         infNivel.setText("Nivel 4");
         PainelConcluido.setVisible(false);
       }
       else if(controle==5){
         B1.setBackground(BLACK);    B2.setBackground(WHITE);    B3.setBackground(WHITE);    B4.setBackground(WHITE);    B5.setBackground(BLACK);
         B6.setBackground(WHITE);    B7.setBackground(BLACK);    B8.setBackground(WHITE);    B9.setBackground(BLACK);    B10.setBackground(WHITE);
         B11.setBackground(BLACK);    B12.setBackground(WHITE);    B13.setBackground(WHITE);    B14.setBackground(BLACK);    B15.setBackground(BLACK);
         B16.setBackground(WHITE);    B17.setBackground(BLACK);    B18.setBackground(WHITE);    B19.setBackground(WHITE);    B20.setBackground(WHITE);
         B21.setBackground(WHITE);    B22.setBackground(WHITE);    B23.setBackground(BLACK);    B24.setBackground(WHITE);    B25.setBackground(BLACK);

           Tela1.setVisible(true);
           auxTrocarCor();
           
         infNivel.setText("Nivel 5");
         PainelConcluido.setVisible(false);
       }
       else if(controle==6){
           PainelConcluido.setVisible(false);
           fim.setVisible(true);
           reset.setVisible(false);
           infNivel.setVisible(false);
       }
    }
    public void auxTrocarCor(){
        func.trocarCor(B1);func.trocarCor(B2);func.trocarCor(B3);func.trocarCor(B4);func.trocarCor(B5);
         func.trocarCor(B6);func.trocarCor(B7);func.trocarCor(B8);func.trocarCor(B9);func.trocarCor(B10);
         func.trocarCor(B11);func.trocarCor(B12);func.trocarCor(B13);func.trocarCor(B14);func.trocarCor(B15);
         func.trocarCor(B16);func.trocarCor(B17);func.trocarCor(B18);func.trocarCor(B19);func.trocarCor(B20);
         func.trocarCor(B21);func.trocarCor(B22);func.trocarCor(B23);func.trocarCor(B24);func.trocarCor(B25);
    }
    public void NivelConcluido(JButton I){
       if(B1.getBackground().equals(WHITE)&&B2.getBackground().equals(WHITE)&&B3.getBackground().equals(WHITE)&&B4.getBackground().equals(WHITE)&&B5.getBackground().equals(WHITE)
            &&B6.getBackground().equals(WHITE)&&B7.getBackground().equals(WHITE)&&B8.getBackground().equals(WHITE)&&B9.getBackground().equals(WHITE)&&B10.getBackground().equals(WHITE)
            &&B11.getBackground().equals(WHITE)&&B12.getBackground().equals(WHITE)&&B13.getBackground().equals(WHITE)&&B14.getBackground().equals(WHITE)&&B15.getBackground().equals(WHITE)
            &&B16.getBackground().equals(WHITE)&&B17.getBackground().equals(WHITE)&&B18.getBackground().equals(WHITE)&&B19.getBackground().equals(WHITE)&&B20.getBackground().equals(WHITE)
            &&B21.getBackground().equals(WHITE)&&B22.getBackground().equals(WHITE)&&B23.getBackground().equals(WHITE)&&B24.getBackground().equals(WHITE)&&B25.getBackground().equals(WHITE)){
           
           
           PainelConcluido.setVisible(true);
           
           controle +=1;
           System.out.println(controle);
           
           Tela1.setVisible(false);
           
       }
    }
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B11;
    private javax.swing.JButton B12;
    private javax.swing.JButton B13;
    private javax.swing.JButton B14;
    private javax.swing.JButton B15;
    private javax.swing.JButton B16;
    private javax.swing.JButton B17;
    private javax.swing.JButton B18;
    private javax.swing.JButton B19;
    private javax.swing.JButton B2;
    private javax.swing.JButton B20;
    private javax.swing.JButton B21;
    private javax.swing.JButton B22;
    private javax.swing.JButton B23;
    private javax.swing.JButton B24;
    private javax.swing.JButton B25;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton BotConcluido;
    private javax.swing.JButton BotLuz;
    private javax.swing.JDesktopPane PainelConcluido;
    private javax.swing.JDesktopPane Tela1;
    private javax.swing.JLabel filmeFim;
    private javax.swing.JDesktopPane fim;
    private javax.swing.JLabel infNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton reset;
    private javax.swing.JLabel saidaConc;
    // End of variables declaration//GEN-END:variables
}
